# Generated by Django 4.0.10 on 2023-03-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('number', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('personname', models.CharField(blank=True, max_length=30, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('jobposition', models.CharField(blank=True, max_length=30, null=True)),
                ('tablenumber', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
